### PR TITLE
Some code reduction + cleanup

### LINKED ISSUE #2295: [BUG] (short description)
### Steps to reproduce

1. Try print with Sd TFT port
2. Try print with Isb TFT port

**Expected behavior**

**Actual behavior**

### Additional Information
* Hello,

first i'm sorry for my english but i'm french and again sorry if i'm in the wrong section but this is the first time i've used a request on github.

I recently installed on my FlSun super Racer a Skr v2 card and a Tft70 from Biqu. However since that time I have had bugs in my printing sometimes the printer stops with the M21 error or the M1 error without having configured a pause in the Slicer. It has also happened to me that printing stops without error on the TFT. I have tried printing with the SD card as well as the USB from the TFT but I have the same concerns however I have no problem securing the USB stick on the motherboard. I have the latest version of TFT as well as the latest version on the motherboard would you have any idea of ​​the problem thanks in advance.

### LINKED ISSUE #2403: [BUG] Hard to update everything after PR #2380
### Description

After PR #2380 the full update of the firmware is very cumbersome. Files get deleted before they are read, backup files (.CUR) are also deleted.

### Steps to reproduce

1. Copy bitmaps, fonts, firmware file, language file, config file to SD Card
2. Reboot TFT

**Expected behavior**
I expect everything to be updated.

**Actual behavior**
 - If icons, fonts, firmware file, language file, config file are new, only fonts, firmware and language file is updated. "config.ini" and, if it was present, "config.ini.CUR" is deleted from SD Card
 - If firmware file and config file is only present, upon reboot only FW updates, "config.ini" gets deleted
 - if only "config.ini" and "language_xx.ini" is present, both get updated but "config.ini.CUR" is not present (not created or deleted if it was there before)
 - icons never get updated
 - config can be updated only if there's no firmware file
 - inf config is updated the firmware backup (.CUR) gets deleted
 - if only firmware is updated config backup (.CUR) gets deleted
 - if only language is updated config backup (.CUR) gets deleted

There can be other quirks but these were enough for me to call it a bug.

### Hardware Variant
BTT TFT35 v3

### TFT Firmware Version & Main Board Firmware details
Latest TFT firmware as of today, SKR v2 (F429) with latest Marlin bugfix as of today.

### PR DESCRIPTION
**Pull request by digant73**
**IMPROVEMENTS:**
* Some code reduction + cleanup after the last merged PRs
* Used TFT* (e.g. TFT28) folder naming convention also for MKS TFTs: There is no more need to rename to MKS folder. README.md file updated accordingly

**BUGFIXES:**
* Fixed missing check on source filename before trying to rename to .CUR during boot: Small bug originated in #2380.

**NOTE:** Reporting #2295 as fixed just to close it (it was fixed by other merged PRs).

fixes #2403
fixes #2295

**PR STATE:** Ready for merge

### CODE REVIEW

File: TFT/src/User/API/Vfs/vfs.c [hunk 1]
```diff
@@ -137,9 +137,7 @@ char * isSupportedFile(char * filename)
   char * extPos = strrchr(filename, '.');  // check last "." in the name where extension is supposed to start
 
   if (extPos != NULL && extPos[1] != 'g' && extPos[1] != 'G')
-  {
     extPos = NULL;
-  }
```
Comment (kisslorand) [inline TFT/src/User/API/Vfs/vfs.c:142]: Please make up your mind, should brackets be used or not at single line "if"...

Comment (digant73) [reply TFT/src/User/API/Vfs/vfs.c:142]: I never used brackets for one line "if" or "if else". Furthermore, all the file is aligned with that convention

File: TFT/src/User/API/Vfs/vfs.c [hunk 2]
```diff
@@ -189,24 +187,20 @@ char * restoreExtension(char * filename)
 
 char * hideFilenameExtension(uint8_t index)
 {
-  char * filename = NULL;
+  char * filename = hideExtension(infoFile.file[index]);
```
[the remark this answers is not in the document]
Comment (digant73) [reply TFT/src/User/API/Vfs/vfs.c:190]: IMHO it is more consistent (apply to all the available filenames)
